name: Deploy Go App to Google Cloud Run with Redis Connector

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: keepa-product-detail-v1
  REGION: us-central1  # 确保与 redis-connector 的区域一致
  VPC_CONNECTOR: redis-connector  # Serverless VPC Access 连接器名称
  REDIS_ADDR: 10.103.208.3:6378
  REDIS_PASSWORD: 2dcff0a8-dbc2-49a7-8aa9-e8991181b08a
  INSTANCE_ID: redis-keepa
  PROJECT_ID: scientific-host-421314
  APP_SCRIPT: https://script.google.com/macros/s/AKfycbyJsRscmYEkFwq88he7AeG6uWQ3qJ8ffGxDpy-LZB_X8vT02K1QAD_G1V8e9ucRyjGY/exec

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 设置 Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 416.0.0'
          skip_install: false

      # 配置 Docker 使用 GCP 认证
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # 构建并推送到 Google Container Registry
      - name: Build and Push Docker image
        run: |
          export IMAGE_NAME=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/my-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 部署到 Cloud Run 并连接 VPC 访问通道
      - name: Deploy to Cloud Run
        if: github.event_name != 'pull_request'
        run: |
          gcloud run deploy keepa-project-detail-${{ github.sha }} \
            --image=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/my-app:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated\
            --port=8080 \
            --memory=256Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --vpc-connector=redis-connector \
            --set-env-vars=REDIS_ADDR=${{ env.REDIS_ADDR }} \
            --set-env-vars=REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} \
            --set-env-vars=PROJECT_ID=${{ env.PROJECT_ID }} \
            --set-env-vars=REGION=${{ env.REGION }} \
            --set-env-vars=INSTANCE_ID=${{ env.INSTANCE_ID }} \
            --set-env-vars=APP_SCRIPT_URL=${{ env.APP_SCRIPT }} 
