name: Deploy Go App to Google Cloud Run with Redis Connector

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: keepa-product-detail-v1
  REGION: us-central1  # 确保与 redis-connector 的区域一致
  VPC_CONNECTOR: redis-connector  # Serverless VPC Access 连接器名称
  REDIS_ADDR: 10.11.16.3:6378
  REDIS_PASSWORD: d2f5bd88-2e92-443f-bf97-5cd14fca4a08
  INSTANCE_ID: keepa-redis
  PROJECT_ID: intrepid-kiln-455107-s1
  KEEPA_MAX_RETRIES: 15
  MAXRETRIES_SLEEP_SEC: 5

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 设置 Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 416.0.0'
          skip_install: false

      # 配置 Docker 使用 GCP 认证
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # 构建并推送到 Google Container Registry
      - name: Build and Push Docker image
        run: |
          export IMAGE_NAME=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/my-app:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # 部署到 Cloud Run 并连接 VPC 访问通道
      - name: Deploy to Cloud Run
        if: github.event_name != 'pull_request'
        run: |
          gcloud run deploy keepa-project-detail-${{ github.sha }} \
            --image=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/my-app:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated\
            --port=8080 \
            --memory=256Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --vpc-connector=redis-connector \
            --set-env-vars=REDIS_ADDR=${{ env.REDIS_ADDR }} \
            --set-env-vars=REDIS_PASSWORD=${{ env.REDIS_PASSWORD }} \
            --set-env-vars=PROJECT_ID=${{ env.PROJECT_ID }} \
            --set-env-vars=REGION=${{ env.REGION }} \
            --set-env-vars=INSTANCE_ID=${{ env.INSTANCE_ID }} \
            --set-env-vars=KEEPA_MAX_RETRIES=${{ env.KEEPA_MAX_RETRIES }} \
            --set-env-vars=MAXRETRIES_SLEEP_SEC=${{ env.MAXRETRIES_SLEEP_SEC }}
