name: Deploy Go App to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: my-go-service  # 替换为您的服务名称
  REGION: us-central1          # 替换为您的区域
  REDIS_PASSWORD: 4fefe278-f03d-4718-955e-6403e30ebc50
  REDIS_HOST: 10.103.208.3:6378  # 替换为您的 Redis 实例的完全限定名
  REDIS_INSTANCE_ID: redis-keepa
  VPC_CONNECTOR: redis-connector

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      # 配置 Docker 以推送镜像到 Google Container Registry
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      # 构建并推送 Docker 镜像
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ env.c }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # 部署到 Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
          platform: managed
          service_account: ${{secrets.CLIENT_EMAIL}}
          allow-unauthenticated: true  # 如果需要公开访问，设为 true
          vpc_connector: ${{ env.VPC_CONNECTOR }}
          env_vars: |
            REDIS_ADDR= ${{env.REDIS_HOST}}
            REDIS_PASSWORD=${{ env.REDIS_PASSWORD }}
            PROJECT_ID=${{secrets.PROJECT_ID}}
            REGION=${{env.REGION}}
            INSTANCE_ID=${{env.REDIS_INSTANCE_ID}}